In [1]:
import pyDOE as pe
import numpy as np
import pandas as pd
import copy
import pymc
import pymc_model as pm

This study is only focusing on glaciers ['03473'] in region [15].
(1, 882) (882,)
[ 0.] (1,)


/home/tushar/anaconda3/envs/pymc/lib/python3.6/site-packages/pandas/core/indexing.py:1472: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


In [2]:
db = pymc.database.pickle.load('diagnostics.pickle')

In [3]:
tempchange = db.trace('tempchange')[:]
precfactor = db.trace('precfactor')[:]
ddfsnow = db.trace('ddfsnow')[:]
massbal = db.trace('mass_bal')[:]

In [ ]:
df = pd.DataFrame({'tempchange': tempchange, 'precfactor': precfactor,
                   'ddfsnow': ddfsnow, 'massbal': massbal})

In [ ]:
df

In [ ]:
sort_df = df.sort_values('massbal')

In [ ]:
sort_df

In [ ]:
sort_df['sorted_index'] = np.arange(len(sort_df))

In [ ]:
sort_df

In [ ]:
lhd = pe.lhs(n=1, samples=10)

In [ ]:
type(lhd)

In [ ]:
lhd

In [ ]:
lhd = (lhd * len(df)).astype(int)

In [ ]:
lhd

In [ ]:
df.iloc(lhd)

In [ ]:
for i in range(len(lhd)):
    lhd[i] = np.asscalar(lhd[i])

In [ ]:
lhd =lhd.ravel()

In [ ]:
lhd

In [ ]:
subset = sort_df.iloc[lhd]

In [ ]:
subset

In [ ]:
subset.index

In [ ]:
subset.sort_index()

In [ ]:
subset_copy = copy.deepcopy(subset)

In [ ]:
subset_copy.

In [ ]:
subset_copy.sort_index(inplace=True)

In [ ]:
subset_copy

In [ ]:
subset

In [4]:
import latin_hypercube as lh

In [9]:
distributions = np.array([tempchange, precfactor, ddfsnow])

In [10]:
ensemble = lh.sample(distributions,
                     samples=300)

copy of argument: [[ 2.05990633 -0.15897178 -0.23857093 ...,  3.4940617   3.03835979
   3.03835979]
 [ 0.14309367  3.12098927  3.12098927 ...,  0.48572879  0.84363392
   0.84363392]
 [ 0.00370843  0.00507734  0.00507734 ...,  0.00435115  0.00435115
   0.00435115]]
copy of sorted argument: [[ -7.41274179e+00  -6.81486345e+00  -6.81486345e+00 ...,   4.73533712e+00
    4.73533712e+00   4.78754367e+00]
 [  8.70010887e-02   1.43093666e-01   1.47081226e-01 ...,   3.18374918e+00
    3.18374918e+00   3.18374918e+00]
 [ -1.38508991e-03  -1.21628631e-03  -1.06617625e-03 ...,   8.53758358e-03
    8.53758358e-03   8.53758358e-03]]
copy of lhs samples: [[  7.31148410e-01   7.40659760e-01   5.91838127e-01]
 [  5.56459352e-01   5.32261747e-01   8.87962679e-01]
 [  3.50044759e-01   3.25667840e-01   7.83795050e-01]
 [  1.82244645e-01   1.60434949e-01   2.01655470e-01]
 [  9.67580524e-01   9.22072809e-02   2.46299800e-01]
 [  7.74924436e-01   8.09905790e-01   8.66327648e-02]
 [  8.01853860e-01   5.07050

2 0 0.00435475152058
2 1 0.00584831186714
2 2 0.00514056662207
2 3 0.00281603486663
2 4 0.00299053057272
2 5 0.00209748155806
2 6 0.00250860155954
2 7 0.00262142682575
2 8 0.00212879448032
2 9 0.00286785588409
2 10 0.00426480301221
2 11 0.00351061971548
2 12 0.00539608346479
2 13 0.00510676425955
2 14 0.00328387209229
2 15 0.0061414223476
2 16 0.00498287554627
2 17 0.003709179423
2 18 0.00394701696442
2 19 0.00555794708132
2 20 0.00543313311442
2 21 0.00663156273049
2 22 0.00455672007734
2 23 0.00668016542773
2 24 0.00419370672346
2 25 0.00500716874664
2 26 0.00436328413169
2 27 0.00241528384664
2 28 0.00314891936711
2 29 0.00220196521022
2 30 0.00319517681547
2 31 0.00328442232561
2 32 0.00304479032839
2 33 0.00258733821754
2 34 0.00311236371713
2 35 0.00441465765321
2 36 0.0021857426729
2 37 0.00705396942722
2 38 0.00370499604406
2 39 0.00143999400783
2 40 0.00469148653022
2 41 0.00537065898481
2 42 0.00288039317799
2 43 0.00586040232001
2 44 0.00158047440572
2 45 0.00559892729667
2 

In [ ]:
import latin_hypercube as lh1

In [8]:
ensemble

array([[ -2.33723732e+00,   1.35722224e+00,   3.78912308e-03,
         -3.97036194e+00],
       [ -9.46602602e-01,   7.67322442e-01,   3.35032950e-03,
         -1.46703930e-02],
       [  3.72610813e-01,   4.85728786e-01,   4.94203516e-03,
          1.36491359e-01],
       ..., 
       [ -2.38516597e+00,   1.45517019e+00,   4.05608192e-03,
         -3.01816303e-02],
       [  1.40017112e+00,   1.71975421e+00,   3.37854392e-03,
         -1.14505509e+00],
       [ -4.04063706e+00,   1.75458586e+00,   5.60040027e-03,
          1.62142410e+00]])

In [16]:
mean = np.mean(ensemble['massbal'])
std = np.std(ensemble['massbal'])

In [17]:
mean, std

(-0.5575608835435785, 1.146286000782126)

In [20]:
pm.observed_massbal, pm.observed_error

(-0.54100000000000004, 0.24299999999999999)