Example to use pymc on a real glacier

In [36]:
import test_model_pymc as tm
import pymc
from pymc import MCMC
import v2_run_calibration_4Tushar as v2
import numpy as np
import latin_hypercube as lh
import pandas as pd
import test_model_pymc as tm

Importing glacer data

In [2]:
db = pymc.database.pickle.load('diagnostics.pickle')

In [3]:
type(db.trace('ddfsnow')[23:450])

numpy.ndarray

In [4]:
distributions = np.array([db.trace('precfactor')[:], db.trace('ddfsnow')[:],
                         db.trace('tempchange')[:]])

In [5]:
type(distributions)

numpy.ndarray

In [48]:
samples = lh.sample(distributions, samples=200)

copy of argument: [[ 0.14309367  3.12098927  3.12098927 ...,  0.48572879  0.84363392
   0.84363392]
 [ 0.00370843  0.00507734  0.00507734 ...,  0.00435115  0.00435115
   0.00435115]
 [ 2.05990633 -0.15897178 -0.23857093 ...,  3.4940617   3.03835979
   3.03835979]]
copy of sorted argument: [[  8.70010887e-02   1.43093666e-01   1.47081226e-01 ...,   3.18374918e+00
    3.18374918e+00   3.18374918e+00]
 [ -1.38508991e-03  -1.21628631e-03  -1.06617625e-03 ...,   8.53758358e-03
    8.53758358e-03   8.53758358e-03]
 [ -7.41274179e+00  -6.81486345e+00  -6.81486345e+00 ...,   4.73533712e+00
    4.73533712e+00   4.78754367e+00]]
copy of lhs samples: [[ 0.86438578  0.58803562  0.55572772]
 [ 0.10747777  0.8085497   0.31593516]
 [ 0.71927167  0.46059911  0.19997015]
 [ 0.3201854   0.43845259  0.0952271 ]
 [ 0.91113011  0.2293557   0.27475961]
 [ 0.78869599  0.12775986  0.281647  ]
 [ 0.2552645   0.24089018  0.09461788]
 [ 0.47238176  0.49873203  0.56673929]
 [ 0.36221713  0.1248143   0.89534899]
 

2 129 -2.62767718906
2 130 0.016130043995
2 131 -2.22328608153
2 132 -3.26399825426
2 133 0.342821419996
2 134 0.465635930183
2 135 2.37003720637
2 136 -2.33391433682
2 137 -1.18100029205
2 138 -2.05821184224
2 139 -6.52461063861
2 140 1.8454829573
2 141 0.119130195102
2 142 -1.7133875949
2 143 1.60989764985
2 144 -2.2904201265
2 145 0.180939186377
2 146 -0.970217392471
2 147 -4.2872773583
2 148 -0.10722851807
2 149 -3.42707517596
2 150 2.48470664856
2 151 2.74031624409
2 152 -0.740158633913
2 153 -0.153131421704
2 154 -2.49376775621
2 155 -0.349764036846
2 156 -0.395812678703
2 157 0.688229054007
2 158 -4.59654403994
2 159 -2.38297905963
2 160 1.12590591574
2 161 1.91423150781
2 162 -1.87269134953
2 163 -2.57662160067
2 164 4.73533712188
2 165 0.51039862777
2 166 3.0244062328
2 167 0.28332694036
2 168 -2.07677372898
2 169 0.741464611155
2 170 0.951919317281
2 171 3.43037084266
2 172 1.17696322951
2 173 -3.16760445248
2 174 -0.382628522089
2 175 0.0740962647366
2 176 2.85250253108
2 17

In [49]:
samples

array([[  1.46353688e+00,   4.34099171e-03,   3.30159444e-03],
       [  5.75762429e-01,   5.29168841e-03,  -1.10772478e+00],
       [  1.24794003e+00,   3.88321206e-03,  -1.83501199e+00],
       [  7.78918382e-01,   3.83500616e-03,  -2.69829230e+00],
       [  1.66360899e+00,   2.90665346e-03,  -1.29980377e+00],
       [  1.34120396e+00,   2.41084706e-03,  -1.24306996e+00],
       [  7.08558949e-01,   2.96977490e-03,  -2.70473227e+00],
       [  9.57532636e-01,   4.02885149e-03,   3.74301793e-02],
       [  8.38951330e-01,   2.37796847e-03,   1.97431102e+00],
       [  1.37752754e+00,   1.25434657e-03,   2.28452621e-01],
       [  9.72177783e-01,   4.36328413e-03,  -4.69425885e-01],
       [  6.20526881e-01,   3.87441546e-03,   2.05158267e+00],
       [  6.57294067e-01,   2.35217413e-03,  -1.45453482e+00],
       [  1.93226757e+00,   4.46644518e-03,  -2.83576727e+00],
       [  4.07388841e-01,   5.36085674e-03,  -5.61427490e-01],
       [  8.76016125e-01,   3.08787260e-03,   1.3580263

In [42]:
samples_df = pd.DataFrame(data=samples, columns=['tempchange', 'ddfsnow', 'precfactor'])

In [18]:
for i in samples_df.index:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [21]:
mass_bal = v2.get_mass_balance_array()[0]

In [23]:
mass_bal

AttributeError: 'numpy.ndarray' object has no attribute 'plot'

In [32]:
type(mass_bal[1])

numpy.float64

In [33]:
def run_massbal_ensemble(parameter_sets):
    matrix = []
    for array in parameter_sets:
        #unpack parameters
        precfactor = array[0]
        ddfsnow = array[1]
        tempchange = array[2]
        
        mass_bal = v2.get_mass_balance_array(precfactor=precfactor, 
                                            tempchange=tempchange,
                                            ddfsnow=ddfsnow)[1]
        
        matrix.append(mass_bal)
        
    return np.array(matrix)
        

In [50]:
ensembles = run_massbal_ensemble(samples)

In [51]:
ensembles

array([-0.18582629, -0.63543657,  0.6430758 ,  0.37521547,  1.07298526,
        0.7221293 ,  0.35416684, -0.73044484, -1.96740218,  0.446919  ,
       -0.449203  , -2.46546528, -0.14319323,  1.95091947, -1.09509179,
       -1.59489903, -1.60528024, -1.20537144, -0.00941031, -0.90673366,
       -0.1319013 ,  0.2237934 , -0.67567044, -1.16031041, -0.6200928 ,
       -0.12788185, -2.52972948, -1.0645952 , -2.02176296, -0.52079395,
       -1.28869681, -0.59227472,  0.38359653,  0.60483399,  0.23514499,
        0.51019388, -0.89107773, -1.84068402, -3.15979523,  1.09486207,
       -0.01390023,  0.13207714,  0.21043056, -0.01298329, -1.62135698,
       -2.94108537, -2.08635642, -0.03240385, -0.2313831 , -2.91480924,
       -0.9884999 , -2.36186132, -1.07228213, -0.93865576,  0.3789382 ,
       -1.56335866, -0.03128977, -1.03884104,  2.15929916,  0.67224782,
       -3.19527952,  0.25231527, -0.92096152, -1.97921806,  0.40705003,
       -0.87148445, -0.40190213, -1.36955233,  0.23476966,  0.86

In [52]:
mean = np.mean(ensembles)
std = np.std(ensembles)

In [53]:
mean, std

(-0.53578295503329987, 1.246617059915921)

In [40]:
tm.observed_massbal, tm.observed_error

(-0.54100000000000004, 0.24299999999999999)

In [ ]:
m = MCMC(tm)

Find index of glacier 15.03473 and 15.03733

In [ ]:
m.sample(iter=1000, burn=0, thin=1)

In [ ]:
m.trace('precfactor')[:]

In [ ]:
m.trace('ddfsnow')[:]

In [ ]:
m.trace('tempchange')[:]

In [ ]:
from pylab import hist, show

In [ ]:
from pymc.Matplot import plot

In [ ]:
plot(m)

In [ ]:
import pymc as pm
from pymc import geweke

In [ ]:
scores = geweke(m)
pm.Matplot.geweke_plot(scores)

In [ ]:
m.summary()

In [ ]:
tm.observed_massbal

In [ ]:
import v2_run_calibration_4Tushar as v2
v2.get_mass_balance(1.074, 0.004, 0.005)

Now generate random sampling using Latin Hypercube of the traces

In [ ]:
precfactor = m.trace('precfactor')[:].copy()
ddfsnow = m.trace('ddfsnow')[:].copy()
tempchange = m.trace('tempchange')[:].copy()

In [ ]:
tempchange.sort()

In [ ]:
tempchange

In [ ]:
import numpy as np
import pyDOE as pe
import latin_hypercube as lh

In [ ]:
x = np.random.normal(0, 2, 100)
y = np.random.normal(1, 0.5, 100)
z = np.random.normal(10, 3, 100)

In [ ]:
dists = np.array([x, y, z])

In [ ]:
dists

In [ ]:
samples = lh.sample(dists, 10)

In [ ]:
num = np.array(i for i in range(0, 10))

In [ ]:
num

In [ ]:
print(num)