Example to use pymc on a real glacier

In [1]:
import test_model_pymc as tm
import pymc
from pymc import MCMC
import v2_run_calibration_4Tushar as v2
import numpy as np
import latin_hypercube as lh
import pandas as pd
import test_model_pymc as tm

This study is only focusing on glaciers ['03473'] in region [15].
(1, 882) (882,)
[ 0.] (1,)


/home/tushar/anaconda3/envs/pymc/lib/python3.6/site-packages/pandas/core/indexing.py:1472: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Importing glacer data

In [2]:
db = pymc.database.pickle.load('diagnostics.pickle')

In [3]:
type(db.trace('ddfsnow')[23:450])

numpy.ndarray

In [4]:
db.trace('mass_bal')[:]

array([-2.90779804,  1.62087329,  1.68804268, ..., -3.81327686,
       -3.15180303, -3.15180303])

In [5]:
distributions = np.array([db.trace('precfactor')[:], db.trace('ddfsnow')[:],
                         db.trace('tempchange')[:]])

In [6]:
type(distributions)

numpy.ndarray

In [7]:
samples = lh.sample(distributions, samples=200)

copy of argument: [[ 0.14309367  3.12098927  3.12098927 ...,  0.48572879  0.84363392
   0.84363392]
 [ 0.00370843  0.00507734  0.00507734 ...,  0.00435115  0.00435115
   0.00435115]
 [ 2.05990633 -0.15897178 -0.23857093 ...,  3.4940617   3.03835979
   3.03835979]]
copy of sorted argument: [[  8.70010887e-02   1.43093666e-01   1.47081226e-01 ...,   3.18374918e+00
    3.18374918e+00   3.18374918e+00]
 [ -1.38508991e-03  -1.21628631e-03  -1.06617625e-03 ...,   8.53758358e-03
    8.53758358e-03   8.53758358e-03]
 [ -7.41274179e+00  -6.81486345e+00  -6.81486345e+00 ...,   4.73533712e+00
    4.73533712e+00   4.78754367e+00]]
copy of lhs samples: [[  8.90947365e-01   1.93270786e-01   2.00384914e-01]
 [  3.88197700e-01   9.77372826e-02   8.83472093e-01]
 [  3.55146287e-01   4.17009357e-01   2.65584111e-01]
 [  8.18376959e-01   4.60818086e-01   8.43888753e-01]
 [  3.03011051e-01   1.84418601e-01   3.00709590e-01]
 [  1.48572476e-02   7.49539793e-01   9.98928912e-01]
 [  4.04683291e-01   7.30463

2 76 -2.77494864862
2 77 2.45118780072
2 78 1.3285150453
2 79 0.798515125932
2 80 -0.37018607094
2 81 -4.59654403994
2 82 -2.57662160067
2 83 -1.11709870589
2 84 0.0740962647366
2 85 -2.21450021221
2 86 0.392987633319
2 87 1.98048092432
2 88 0.944683966225
2 89 -0.318635782959
2 90 -1.43983356933
2 91 0.615800628688
2 92 -1.26026873882
2 93 -2.30737094827
2 94 -0.611233688647
2 95 -2.48358070834
2 96 -0.387269633235
2 97 -3.70220611544
2 98 -3.16760445248
2 99 0.170541627181
2 100 0.426301768465
2 101 -0.468756451623
2 102 0.644211883115
2 103 -2.14344391528
2 104 -0.0687391422098
2 105 -3.94998614332
2 106 1.04572342805
2 107 -1.76391619598
2 108 0.300015353077
2 109 0.716922394987
2 110 -2.83073772219
2 111 -0.24272243422
2 112 2.65447421131
2 113 0.768648377284
2 114 -2.62672923838
2 115 -1.40009436447
2 116 3.24479251007
2 117 0.00698217306575
2 118 1.0181693708
2 119 2.02513559864
2 120 -1.92673621313
2 121 -1.23612848001
2 122 0.772234690154
2 123 -2.66291058801
2 124 0.471950040

In [49]:
samples

array([[  1.46353688e+00,   4.34099171e-03,   3.30159444e-03],
       [  5.75762429e-01,   5.29168841e-03,  -1.10772478e+00],
       [  1.24794003e+00,   3.88321206e-03,  -1.83501199e+00],
       [  7.78918382e-01,   3.83500616e-03,  -2.69829230e+00],
       [  1.66360899e+00,   2.90665346e-03,  -1.29980377e+00],
       [  1.34120396e+00,   2.41084706e-03,  -1.24306996e+00],
       [  7.08558949e-01,   2.96977490e-03,  -2.70473227e+00],
       [  9.57532636e-01,   4.02885149e-03,   3.74301793e-02],
       [  8.38951330e-01,   2.37796847e-03,   1.97431102e+00],
       [  1.37752754e+00,   1.25434657e-03,   2.28452621e-01],
       [  9.72177783e-01,   4.36328413e-03,  -4.69425885e-01],
       [  6.20526881e-01,   3.87441546e-03,   2.05158267e+00],
       [  6.57294067e-01,   2.35217413e-03,  -1.45453482e+00],
       [  1.93226757e+00,   4.46644518e-03,  -2.83576727e+00],
       [  4.07388841e-01,   5.36085674e-03,  -5.61427490e-01],
       [  8.76016125e-01,   3.08787260e-03,   1.3580263

In [42]:
samples_df = pd.DataFrame(data=samples, columns=['tempchange', 'ddfsnow', 'precfactor'])

In [18]:
for i in samples_df.index:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [21]:
mass_bal = v2.get_mass_balance_array()[0]

In [23]:
mass_bal

AttributeError: 'numpy.ndarray' object has no attribute 'plot'

In [32]:
type(mass_bal[1])

numpy.float64

In [8]:
def run_massbal_ensemble(parameter_sets):
    matrix = []
    for array in parameter_sets:
        #unpack parameters
        precfactor = array[0]
        ddfsnow = array[1]
        tempchange = array[2]
        
        mass_bal = v2.get_mass_balance_array(precfactor=precfactor, 
                                            tempchange=tempchange,
                                            ddfsnow=ddfsnow)[1]
        
        matrix.append(mass_bal)
        
    return np.array(matrix)
        

In [9]:
ensembles = run_massbal_ensemble(samples)

In [10]:
ensembles

array([ 1.22353387, -1.85616739, -0.10924284, -1.36981242, -0.18634016,
       -4.99754845, -0.6370328 , -2.69974874,  0.39623938, -0.65851958,
        1.5306202 , -0.44073309,  0.49922427, -2.87447022,  0.53695407,
       -2.79933599, -1.24771186, -1.23626741,  0.42368923,  0.035283  ,
        0.5365845 ,  3.45060395, -0.46589593, -2.47220093, -1.58198061,
        0.21222026,  0.60146887, -0.33853875,  0.4028808 ,  0.60979533,
        0.60915957,  0.75233649, -0.0105064 ,  0.69139463, -0.91296428,
       -0.71956048, -1.83079664,  0.216139  , -0.45005217, -1.27673676,
        0.12607489, -0.4160761 , -0.3969191 ,  0.83123277, -0.89665676,
       -0.53410185, -0.70964051, -2.48483626, -1.03846245, -1.58227167,
       -1.35113456, -1.91279774, -0.81004154, -0.48982351, -1.18593728,
       -1.27017685,  3.1268326 , -0.38302148, -0.92544087, -0.53627514,
        1.1947293 , -3.54988416,  0.59839381, -0.16133759, -1.9933489 ,
        0.20232541, -1.32989958, -0.53146238, -2.32448371, -0.11

In [11]:
mean = np.mean(ensembles)
std = np.std(ensembles)

In [12]:
mean, std

(-0.54113115707218262, 1.1997196570784645)

In [13]:
tm.observed_massbal, tm.observed_error

(-0.54100000000000004, 0.24299999999999999)

In [14]:
db1 = pymc.database.pickle.load('diagnostics.pickle')
distributions1 =  np.array([db.trace('precfactor')[:], db.trace('ddfsnow')[:],
                         db.trace('tempchange')[:]])
samples1 = lh.sample(distributions1, samples=200)
ensembles1 = run_massbal_ensemble(samples1)
mean1 = np.mean(ensembles1)
std1 = np.std(ensembles1)

copy of argument: [[ 0.14309367  3.12098927  3.12098927 ...,  0.48572879  0.84363392
   0.84363392]
 [ 0.00370843  0.00507734  0.00507734 ...,  0.00435115  0.00435115
   0.00435115]
 [ 2.05990633 -0.15897178 -0.23857093 ...,  3.4940617   3.03835979
   3.03835979]]
copy of sorted argument: [[  8.70010887e-02   1.43093666e-01   1.47081226e-01 ...,   3.18374918e+00
    3.18374918e+00   3.18374918e+00]
 [ -1.38508991e-03  -1.21628631e-03  -1.06617625e-03 ...,   8.53758358e-03
    8.53758358e-03   8.53758358e-03]
 [ -7.41274179e+00  -6.81486345e+00  -6.81486345e+00 ...,   4.73533712e+00
    4.73533712e+00   4.78754367e+00]]
copy of lhs samples: [[ 0.45471164  0.91716631  0.62785944]
 [ 0.59397899  0.0466581   0.30022272]
 [ 0.06848049  0.50336855  0.99587372]
 [ 0.24107988  0.38149791  0.35508626]
 [ 0.47596068  0.91212038  0.01057324]
 [ 0.54300498  0.20214106  0.92861496]
 [ 0.65146981  0.18199517  0.71386543]
 [ 0.30376102  0.45881542  0.90311112]
 [ 0.66093492  0.13544564  0.47948528]
 

2 155 -0.864815455108
2 156 1.33010175952
2 157 1.02666634258
2 158 -0.307939826262
2 159 -2.41771126898
2 160 0.0197259455902
2 161 0.236038113202
2 162 -0.793957527475
2 163 1.73562493998
2 164 -2.96554915504
2 165 -1.86338672275
2 166 -2.6283115882
2 167 -0.550020931674
2 168 1.45133844968
2 169 -1.40009436447
2 170 0.110965686117
2 171 -0.18611730202
2 172 0.839454412494
2 173 1.41317018519
2 174 1.68532405351
2 175 -1.94274709249
2 176 1.57141253271
2 177 -0.311205072382
2 178 -1.76555131345
2 179 -0.0551596116584
2 180 -2.14344391528
2 181 0.852609626449
2 182 1.4374760048
2 183 1.21199114458
2 184 -0.117793055938
2 185 -0.0291357634854
2 186 1.8846981064
2 187 -1.11407371628
2 188 -1.4454511316
2 189 -1.8198900527
2 190 -1.07964439126
2 191 1.54290606273
2 192 2.43922425125
2 193 -1.5364359142
2 194 -1.19722471245
2 195 0.763701767503
2 196 -1.90413292588
2 197 -1.07236733051
2 198 0.462240901191
2 199 1.12280603196
[[  9.47901889e-01   6.09671773e-03   3.50400028e-01]
 [  1.094

In [15]:
mean1, std1

(-0.55440607702587386, 1.1825411569683082)

In [16]:
w_mean = np.mean(db.trace('mass_bal')[:])
w_std = np.std(db.trace('mass_bal')[:])
w_mean, w_std

(-0.55816105985096953, 1.1479416479599114)

In [ ]:
m = MCMC(tm)

Find index of glacier 15.03473 and 15.03733

In [ ]:
m.sample(iter=1000, burn=0, thin=1)

In [ ]:
m.trace('precfactor')[:]

In [ ]:
m.trace('ddfsnow')[:]

In [ ]:
m.trace('tempchange')[:]

In [ ]:
from pylab import hist, show

In [ ]:
from pymc.Matplot import plot

In [ ]:
plot(m)

In [ ]:
import pymc as pm
from pymc import geweke

In [ ]:
scores = geweke(m)
pm.Matplot.geweke_plot(scores)

In [ ]:
m.summary()

In [ ]:
tm.observed_massbal

In [ ]:
import v2_run_calibration_4Tushar as v2
v2.get_mass_balance(1.074, 0.004, 0.005)

Now generate random sampling using Latin Hypercube of the traces

In [ ]:
precfactor = m.trace('precfactor')[:].copy()
ddfsnow = m.trace('ddfsnow')[:].copy()
tempchange = m.trace('tempchange')[:].copy()

In [ ]:
tempchange.sort()

In [ ]:
tempchange

In [ ]:
import numpy as np
import pyDOE as pe
import latin_hypercube as lh

In [ ]:
x = np.random.normal(0, 2, 100)
y = np.random.normal(1, 0.5, 100)
z = np.random.normal(10, 3, 100)

In [ ]:
dists = np.array([x, y, z])

In [ ]:
dists

In [ ]:
samples = lh.sample(dists, 10)

In [ ]:
num = np.array(i for i in range(0, 10))

In [ ]:
num

In [ ]:
print(num)