In [1]:
import numpy as np
import pandas as pd
import xarray as xr

In [5]:
a = np.arange(20)

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
(a > 10)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [8]:
b = np.arange(10, 20)

In [12]:
(a.isin(b))

AttributeError: 'numpy.ndarray' object has no attribute 'isin'

In [10]:
a < 30

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [6]:
ds = xr.open_dataset('../MCMC_Data/testfile.nc')

In [7]:
ds

<xarray.Dataset>
Dimensions:    (runs: 10, variables: 9)
Coordinates:
  * runs       (runs) int64 0 1 2 3 4 5 6 7 8 9
  * variables  (variables) object 'tempchange' 'precfactor' 'ddfsnow' ...
Data variables:
    15.03473   (runs, variables) float64 ...
    15.03733   (runs, variables) float64 ...

In [47]:
ds['15.03473']

<xarray.DataArray '15.03473' (runs: 10, variables: 9)>
array([[ -3.589412e-01,   9.446376e-01,   4.277947e-03,  -5.357972e-01,
         -6.500000e-03,  -6.500000e-03,   1.000000e-04,   5.857143e-03,
          1.000000e+00],
       [ -1.734766e-01,   9.446376e-01,   4.277947e-03,  -6.423281e-01,
         -6.500000e-03,  -6.500000e-03,   1.000000e-04,   5.857143e-03,
          1.000000e+00],
       [ -4.846557e-01,   9.446376e-01,   4.277947e-03,  -4.654138e-01,
         -6.500000e-03,  -6.500000e-03,   1.000000e-04,   5.857143e-03,
          1.000000e+00],
       [ -1.032601e+00,   9.446376e-01,   3.734953e-03,  -1.257188e-01,
         -6.500000e-03,  -6.500000e-03,   1.000000e-04,   5.857143e-03,
          1.000000e+00],
       [ -2.692509e-01,   9.446376e-01,   3.734953e-03,  -5.361216e-01,
         -6.500000e-03,  -6.500000e-03,   1.000000e-04,   5.857143e-03,
          1.000000e+00],
       [ -4.845924e-01,   7.028247e-01,   3.534700e-03,  -6.874605e-01,
         -6.500000e-03,  -6.

In [61]:
ds.sizes['runs']

10

In [33]:
ds['15.03473'][1].coords

Coordinates:
    runs       int64 1
  * variables  (variables) object 'tempchange' 'precfactor' 'ddfsnow' ...

In [39]:
df = ds['15.03473'].to_pandas()

In [46]:
df.loc[1]['tempchange']

-0.17347663823588247

In [86]:
df.name = "1"

In [87]:
df.name

'1'

In [89]:
df1 = pd.read_csv('../MCMC_Data/config/15.01551.csv')

In [91]:
df1.name = 

AttributeError: 'DataFrame' object has no attribute 'name'

In [50]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [100]:
test = xr.open_dataset('../Output/PyGEM_R15_MPI-ESM-LR_rcp26_biasadj_opt2_1995_2015_all.nc')

In [111]:
test.sel({'glac_idx':1, 'sim':1})['massbaltotal_glac_monthly'][1]

<xarray.DataArray 'massbaltotal_glac_monthly' ()>
array(0.019792826498773224)
Coordinates:
    sim       int32 1
    glac_idx  int32 1
    time      datetime64[ns] 1999-11-01
Attributes:
    long_name:  glacier-wide total mass balance
    units:      m w.e.
    comment:    total mass balance is the sum of the climatic mass balance an...

In [81]:
test.isel({'glac_idx':0})

<xarray.Dataset>
Dimensions:                       (elevbin: 882, glac_table: 18, sim: 10, time: 192, year: 16, year_plus1: 17)
Coordinates:
  * sim                           (sim) int32 0 1 2 3 4 5 6 7 8 9
    glac_idx                      int32 0
  * time                          (time) datetime64[ns] 1999-10-01 ...
  * year                          (year) int32 2000 2001 2002 2003 2004 2005 ...
  * year_plus1                    (year_plus1) int32 2000 2001 2002 2003 ...
  * elevbin                       (elevbin) int32 5 15 25 35 45 55 65 75 85 ...
Dimensions without coordinates: glac_table
Data variables:
    glacier_table_header          (glac_table) object ...
    glacier_table                 (glac_table) float64 ...
    temp_glac_monthly             (time, sim) float64 ...
    prec_glac_monthly             (time, sim) float64 ...
    acc_glac_monthly              (time, sim) float64 ...
    refreeze_glac_monthly         (time, sim) float64 ...
    melt_glac_monthly             

In [92]:
ds1 = xr.open_dataset('../MCMC_Data/config/15.01551.nc')

In [99]:
ds1['15.01551']

<xarray.DataArray '15.01551' (runs: 10, variables: 9)>
array([[  2.022473e+00,   7.669604e-01,   6.277011e-03,   1.006087e+00,
         -6.500000e-03,  -6.500000e-03,   1.000000e-04,   5.857143e-03,
          1.000000e+00],
       [  2.022473e+00,   7.669604e-01,   6.277011e-03,   1.006087e+00,
         -6.500000e-03,  -6.500000e-03,   1.000000e-04,   5.857143e-03,
          1.000000e+00],
       [  2.022473e+00,   6.648724e-01,   6.277011e-03,   7.522508e-01,
         -6.500000e-03,  -6.500000e-03,   1.000000e-04,   5.857143e-03,
          1.000000e+00],
       [  2.022473e+00,   6.648724e-01,   6.277011e-03,   7.522508e-01,
         -6.500000e-03,  -6.500000e-03,   1.000000e-04,   5.857143e-03,
          1.000000e+00],
       [  2.022473e+00,   5.639015e-01,   6.277011e-03,   5.011929e-01,
         -6.500000e-03,  -6.500000e-03,   1.000000e-04,   5.857143e-03,
          1.000000e+00],
       [  2.022473e+00,   5.639015e-01,   6.277011e-03,   5.011929e-01,
         -6.500000e-03,  -6.

In [96]:
name = '15.01551.nc'

In [98]:
name[:-3]

'15.01551'

In [2]:
csv_path = '../DEMs/hma_mb_20171211_1343.csv'

In [3]:
df = pd.read_csv(csv_path)

In [4]:
df

RGIId            x            y     z_med     z_p16     z_p84  \
0      15.10075   191166.812  -893197.316  6685.077  6575.304  6752.220   
1      15.10079   191933.822  -887365.269  6639.969  6574.278  6716.535   
2      15.10059   189340.252  -890870.902  6509.042  6389.264  6717.535   
3      15.10060   189418.505  -890223.859  6451.761  6213.701  6666.301   
4      15.09929   168255.157  -872992.369  6421.664  6319.710  6478.960   
5      15.09801   193520.116  -886474.502  6418.253  6154.812  6680.712   
6      15.10055   188856.790  -893215.913  6387.981  6094.955  6700.276   
7      15.10070   190496.296  -887732.672  6386.423  6214.353  6633.506   
8      13.26246   515570.725  -860770.312  6382.412  6151.811  6567.304   
9      15.09802   193509.313  -889146.460  6348.359  6142.358  6602.849   
10     15.01551   746606.198  -860224.831  6332.946  6306.034  6350.280   
11     13.26247   515969.157  -862258.896  6330.832  6068.613  6584.505   
12     15.09995   178573.836  -887272.025  6329.124  6281.949  6392.737   
13     13.37610  -306897.639   -61115.362  6327.264  5590.569  6439.152   
14     13.51756  -502233.238  -203195.706  6294.667  6178.842  6393.363   
15     15.10712   519434.082  -859466.568  6276.996  6229.578  6297.841   
16     15.10206   166150.827  -873326.176  6274.422  6222.661  6318.864   
17     15.10228   130353.926  -859241.345  6271.377  6105.025  6364.441   
18     15.10188   162563.043  -878163.639  6266.163  6070.450  6421.195   
19     15.10174   159654.614  -878955.542  6266.102  6204.647  6327.504   
20     14.26918  -518588.069  -541932.891  6258.312  6244.306  6280.653   
21     15.09946   171202.754  -882739.952  6257.611  6112.551  6354.815   
22     13.26239   512157.097  -865478.196  6255.941  5607.706  6615.657   
23     15.10068   190423.305  -880580.891  6254.758  6050.098  6311.788   
24     15.09927   168371.705  -877648.780  6253.284  6146.402  6366.993   
25     15.10234   133412.858  -859918.266  6251.799  6168.916  6340.035   
26     15.09804   195028.697  -890132.161  6244.344  6088.227  6360.443   
27     13.51799  -484124.256  -185249.242  6242.459  6156.231  6332.618   
28     15.09942   171169.336  -883389.572  6241.364  6075.407  6414.681   
29     13.26648   -49109.647  -807242.878  6235.711  6182.946  6273.235   
...         ...          ...          ...       ...       ...       ...   
10619  13.18302 -1193480.988   426265.891  3291.196  3150.519  3423.717   
10620  13.05512  -377402.959  1036597.215  3280.891  3225.309  3386.658   
10621  13.05580  -449314.839  1015789.414  3279.471  3200.355  3354.572   
10622  13.05428  -430417.944   993669.510  3278.381  3210.435  3335.690   
10623  13.29364  -116704.103   900174.882  3272.473  3253.371  3304.798   
10624  13.05613  -459747.226  1024665.796  3266.367  3004.586  3331.999   
10625  13.05579  -448086.626  1014683.502  3262.023  3171.599  3364.087   
10626  13.05581  -449833.360  1016531.282  3260.145  3166.400  3351.183   
10627  13.04841  -302903.640  1046907.747  3253.099  3212.112  3299.499   
10628  13.05617  -461496.896  1025885.281  3245.605  3157.252  3328.037   
10629  13.05584  -450960.757  1017895.066  3241.339  3128.914  3313.833   
10630  13.05599  -454553.119  1018702.657  3239.066  3166.249  3335.935   
10631  13.18305 -1187274.793   423596.378  3223.185  3118.760  3309.466   
10632  13.05756  -456259.063  1019132.006  3218.554  3132.723  3316.914   
10633  13.05583  -452030.492  1018269.091  3217.471  3146.645  3299.916   
10634  13.04846  -305832.644  1058149.620  3211.030  3132.212  3321.879   
10635  13.05588  -446374.070  1018300.346  3202.979  3122.000  3252.005   
10636  13.05596  -454782.341  1020691.132  3192.398  3151.826  3256.184   
10637  13.05595  -453634.856  1020755.092  3177.613  3141.133  3227.667   
10638  13.05603  -459322.244  1020129.466  3177.423  3120.755  3252.894   
10639  13.05755  -455424.568  1019044.217  3176.037  3054.545  3267.372   
10640  13.05604  -459994.934  10199

In [38]:
d1 = df.loc[(df['RGIId'] >= 13) ]

In [39]:
d1 

RGIId            x            y     z_med     z_p16     z_p84  \
0      15.10075   191166.812  -893197.316  6685.077  6575.304  6752.220   
1      15.10079   191933.822  -887365.269  6639.969  6574.278  6716.535   
2      15.10059   189340.252  -890870.902  6509.042  6389.264  6717.535   
3      15.10060   189418.505  -890223.859  6451.761  6213.701  6666.301   
4      15.09929   168255.157  -872992.369  6421.664  6319.710  6478.960   
5      15.09801   193520.116  -886474.502  6418.253  6154.812  6680.712   
6      15.10055   188856.790  -893215.913  6387.981  6094.955  6700.276   
7      15.10070   190496.296  -887732.672  6386.423  6214.353  6633.506   
8      13.26246   515570.725  -860770.312  6382.412  6151.811  6567.304   
9      15.09802   193509.313  -889146.460  6348.359  6142.358  6602.849   
10     15.01551   746606.198  -860224.831  6332.946  6306.034  6350.280   
11     13.26247   515969.157  -862258.896  6330.832  6068.613  6584.505   
12     15.09995   178573.836  -887272.025  6329.124  6281.949  6392.737   
13     13.37610  -306897.639   -61115.362  6327.264  5590.569  6439.152   
14     13.51756  -502233.238  -203195.706  6294.667  6178.842  6393.363   
15     15.10712   519434.082  -859466.568  6276.996  6229.578  6297.841   
16     15.10206   166150.827  -873326.176  6274.422  6222.661  6318.864   
17     15.10228   130353.926  -859241.345  6271.377  6105.025  6364.441   
18     15.10188   162563.043  -878163.639  6266.163  6070.450  6421.195   
19     15.10174   159654.614  -878955.542  6266.102  6204.647  6327.504   
20     14.26918  -518588.069  -541932.891  6258.312  6244.306  6280.653   
21     15.09946   171202.754  -882739.952  6257.611  6112.551  6354.815   
22     13.26239   512157.097  -865478.196  6255.941  5607.706  6615.657   
23     15.10068   190423.305  -880580.891  6254.758  6050.098  6311.788   
24     15.09927   168371.705  -877648.780  6253.284  6146.402  6366.993   
25     15.10234   133412.858  -859918.266  6251.799  6168.916  6340.035   
26     15.09804   195028.697  -890132.161  6244.344  6088.227  6360.443   
27     13.51799  -484124.256  -185249.242  6242.459  6156.231  6332.618   
28     15.09942   171169.336  -883389.572  6241.364  6075.407  6414.681   
29     13.26648   -49109.647  -807242.878  6235.711  6182.946  6273.235   
...         ...          ...          ...       ...       ...       ...   
10619  13.18302 -1193480.988   426265.891  3291.196  3150.519  3423.717   
10620  13.05512  -377402.959  1036597.215  3280.891  3225.309  3386.658   
10621  13.05580  -449314.839  1015789.414  3279.471  3200.355  3354.572   
10622  13.05428  -430417.944   993669.510  3278.381  3210.435  3335.690   
10623  13.29364  -116704.103   900174.882  3272.473  3253.371  3304.798   
10624  13.05613  -459747.226  1024665.796  3266.367  3004.586  3331.999   
10625  13.05579  -448086.626  1014683.502  3262.023  3171.599  3364.087   
10626  13.05581  -449833.360  1016531.282  3260.145  3166.400  3351.183   
10627  13.04841  -302903.640  1046907.747  3253.099  3212.112  3299.499   
10628  13.05617  -461496.896  1025885.281  3245.605  3157.252  3328.037   
10629  13.05584  -450960.757  1017895.066  3241.339  3128.914  3313.833   
10630  13.05599  -454553.119  1018702.657  3239.066  3166.249  3335.935   
10631  13.18305 -1187274.793   423596.378  3223.185  3118.760  3309.466   
10632  13.05756  -456259.063  1019132.006  3218.554  3132.723  3316.914   
10633  13.05583  -452030.492  1018269.091  3217.471  3146.645  3299.916   
10634  13.04846  -305832.644  1058149.620  3211.030  3132.212  3321.879   
10635  13.05588  -446374.070  1018300.346  3202.979  3122.000  3252.005   
10636  13.05596  -454782.341  1020691.132  3192.398  3151.826  3256.184   
10637  13.05595  -453634.856  1020755.092  3177.613  3141.133  3227.667   
10638  13.05603  -459322.244  1020129.466  3177.423  3120.755  3252.894   
10639  13.05755  -455424.568  1019044.217  3176.037  3054.545  3267.372   
10640  13.05604  -459994.934  10199

In [40]:
d2 = d1.loc[d1['RGIId'] < 14]

In [37]:
d2

RGIId            x            y     z_med     z_p16     z_p84  \
8      13.26246   515570.725  -860770.312  6382.412  6151.811  6567.304   
11     13.26247   515969.157  -862258.896  6330.832  6068.613  6584.505   
13     13.37610  -306897.639   -61115.362  6327.264  5590.569  6439.152   
14     13.51756  -502233.238  -203195.706  6294.667  6178.842  6393.363   
22     13.26239   512157.097  -865478.196  6255.941  5607.706  6615.657   
27     13.51799  -484124.256  -185249.242  6242.459  6156.231  6332.618   
29     13.26648   -49109.647  -807242.878  6235.711  6182.946  6273.235   
30     13.26242   513696.995  -860038.288  6235.011  6129.341  6305.902   
33     13.37592  -324629.677   -54805.059  6229.910  6070.809  6347.251   
36     13.26240   513089.416  -859359.786  6228.697  6147.015  6285.817   
38     13.26897  -217698.560  -687876.129  6226.109  6039.793  6363.110   
47     13.51758  -502567.908  -210365.740  6207.235  6163.163  6245.220   
50     13.37473  -363709.464    -3090.508  6196.976  6180.209  6211.780   
53     13.26426   493404.932  -866839.685  6186.783  6029.656  6525.429   
56     13.26587   -70207.822  -796575.224  6183.704  6116.753  6240.381   
57     13.36906  -309645.963   -72553.430  6182.407  6018.486  6269.687   
58     13.26594   -60397.792  -800541.561  6179.191  5939.331  6415.974   
59     13.26977  -268690.524  -635073.898  6178.579  6068.929  6379.213   
60     13.26237   503844.683  -864415.195  6178.183  5856.646  6610.926   
61     13.53982   -27633.022    82520.567  6176.682  6117.787  6211.234   
67     13.36917  -306111.853   -64622.730  6168.026  5985.548  6348.323   
69     13.37727  -368429.685   -52018.273  6166.896  5831.838  6363.085   
72     13.37590  -325420.335   -54030.086  6164.632  5979.863  6254.040   
80     13.37586  -327457.484   -51089.578  6154.255  6015.209  6264.920   
82     13.26238   508496.026  -863825.187  6149.397  6038.140  6245.237   
87     13.00232  -494785.256  -160537.302  6144.734  6065.563  6218.242   
88     13.00595  -546208.013   -77850.699  6143.600  6017.991  6234.085   
91     13.26595   -59843.695  -797489.350  6140.142  6039.489  6215.161   
92     13.53244  -320909.922   -69481.777  6139.911  5946.901  6224.282   
94     13.52144  -541766.130  -195460.973  6135.926  6113.460  6151.227   
...         ...          ...          ...       ...       ...       ...   
10619  13.18302 -1193480.988   426265.891  3291.196  3150.519  3423.717   
10620  13.05512  -377402.959  1036597.215  3280.891  3225.309  3386.658   
10621  13.05580  -449314.839  1015789.414  3279.471  3200.355  3354.572   
10622  13.05428  -430417.944   993669.510  3278.381  3210.435  3335.690   
10623  13.29364  -116704.103   900174.882  3272.473  3253.371  3304.798   
10624  13.05613  -459747.226  1024665.796  3266.367  3004.586  3331.999   
10625  13.05579  -448086.626  1014683.502  3262.023  3171.599  3364.087   
10626  13.05581  -449833.360  1016531.282  3260.145  3166.400  3351.183   
10627  13.04841  -302903.640  1046907.747  3253.099  3212.112  3299.499   
10628  13.05617  -461496.896  1025885.281  3245.605  3157.252  3328.037   
10629  13.05584  -450960.757  1017895.066  3241.339  3128.914  3313.833   
10630  13.05599  -454553.119  1018702.657  3239.066  3166.249  3335.935   
10631  13.18305 -1187274.793   423596.378  3223.185  3118.760  3309.466   
10632  13.05756  -456259.063  1019132.006  3218.554  3132.723  3316.914   
10633  13.05583  -452030.492  1018269.091  3217.471  3146.645  3299.916   
10634  13.04846  -305832.644  1058149.620  3211.030  3132.212  3321.879   
10635  13.05588  -446374.070  1018300.346  3202.979  3122.000  3252.005   
10636  13.05596  -454782.341  1020691.132  3192.398  3151.826  3256.184   
10637  13.05595  -453634.856  1020755.092  3177.613  3141.133  3227.667   
10638  13.05603  -459322.244  1020129.466  3177.423  3120.755  3252.894   
10639  13.05755  -455424.568  1019044.217  3176.037  3054.545  3267.372   
10640  13.05604  -459994.934  10199

In [15]:
numbers = d1['RGIId'] % 1

In [20]:
numbers_round = numbers.round(5)

In [30]:
type(numbers_round.astype(str)[2])

str

In [51]:
def get_shean_glacier_nos(region_no):
    
    # safety, convert input to int
    region_no = int(region_no)
    
    # get shean's data, convert to dataframe, get 
    # glacier numbers
    csv_path = '../DEMs/hma_mb_20171211_1343.csv'
    df = pd.read_csv(csv_path)
    rgi = df['RGIId']
    
    # select only glaciers in specified region no
    rgi = rgi.loc[rgi >= region_no]
    rgi = rgi.loc[rgi < (region_no + 1)]
    
    # get only glacier numbers, convert to string
    num = rgi % 1
    num = num.round(5)
    num = num.astype(str)
    
    # slice string to remove decimal
    num = [n[2:] for n in num]
    
    # make sure there are 5 digits
    for i in range(len(num)):
        while len(num[i]) < 5:
            num[i] += '0'
    
    return num
    

In [52]:
get_shean_glacier_nos(15)

['10075',
 '10079',
 '10059',
 '10060',
 '09929',
 '09801',
 '10055',
 '10070',
 '09802',
 '01551',
 '09995',
 '10712',
 '10206',
 '10228',
 '10188',
 '10174',
 '09946',
 '10068',
 '09927',
 '10234',
 '09804',
 '09942',
 '10054',
 '10970',
 '03613',
 '10056',
 '10194',
 '10040',
 '09975',
 '09920',
 '10181',
 '10193',
 '09921',
 '10240',
 '09953',
 '09962',
 '11000',
 '10032',
 '10030',
 '09923',
 '10973',
 '10132',
 '10024',
 '10001',
 '10042',
 '09829',
 '10196',
 '10185',
 '09807',
 '10243',
 '10366',
 '09924',
 '10413',
 '09010',
 '09805',
 '10229',
 '10157',
 '10178',
 '10971',
 '10205',
 '03618',
 '09810',
 '09806',
 '10130',
 '10171',
 '10519',
 '10261',
 '04382',
 '09931',
 '09824',
 '10256',
 '10446',
 '09832',
 '09925',
 '10426',
 '09815',
 '10517',
 '10047',
 '10442',
 '08980',
 '03729',
 '11022',
 '10037',
 '10173',
 '10201',
 '09819',
 '10513',
 '03617',
 '10975',
 '10489',
 '09934',
 '09958',
 '10195',
 '10716',
 '09967',
 '09948',
 '10161',
 '10974',
 '10129',
 '10189',


In [47]:
return numbers_round[2]

SyntaxError: 'return' outside function (<ipython-input-47-ff526827005c>, line 1)

In [24]:
numlist = numbers_round.tolist()

In [25]:
numlist

[0.10075,
 0.10079,
 0.10059,
 0.1006,
 0.09929,
 0.09801,
 0.10055,
 0.1007,
 0.09802,
 0.01551,
 0.09995,
 0.10712,
 0.10206,
 0.10228,
 0.10188,
 0.10174,
 0.09946,
 0.10068,
 0.09927,
 0.10234,
 0.09804,
 0.09942,
 0.10054,
 0.1097,
 0.03613,
 0.10056,
 0.10194,
 0.1004,
 0.09975,
 0.0992,
 0.10181,
 0.10193,
 0.09921,
 0.1024,
 0.09953,
 0.09962,
 0.11,
 0.10032,
 0.1003,
 0.09923,
 0.10973,
 0.10132,
 0.10024,
 0.10001,
 0.10042,
 0.09829,
 0.10196,
 0.10185,
 0.09807,
 0.10243,
 0.10366,
 0.09924,
 0.10413,
 0.0901,
 0.09805,
 0.10229,
 0.10157,
 0.10178,
 0.10971,
 0.10205,
 0.03618,
 0.0981,
 0.09806,
 0.1013,
 0.10171,
 0.10519,
 0.10261,
 0.04382,
 0.09931,
 0.09824,
 0.10256,
 0.10446,
 0.09832,
 0.09925,
 0.10426,
 0.09815,
 0.10517,
 0.10047,
 0.10442,
 0.0898,
 0.03729,
 0.11022,
 0.10037,
 0.10173,
 0.10201,
 0.09819,
 0.10513,
 0.03617,
 0.10975,
 0.10489,
 0.09934,
 0.09958,
 0.10195,
 0.10716,
 0.09967,
 0.09948,
 0.10161,
 0.10974,
 0.10129,
 0.10189,
 0.10388,
 0.0

In [16]:
strings = numbers.tolist()

In [17]:
strings

[0.10074999999999967,
 0.10078999999999994,
 0.10058999999999862,
 0.10060000000000002,
 0.09928999999999988,
 0.09801000000000037,
 0.10055000000000014,
 0.10069999999999979,
 0.09802000000000177,
 0.015510000000000801,
 0.09994999999999976,
 0.10712000000000188,
 0.10205999999999982,
 0.1022799999999986,
 0.10187999999999953,
 0.1017399999999995,
 0.09946000000000055,
 0.10067999999999877,
 0.09927000000000064,
 0.10233999999999988,
 0.09803999999999924,
 0.09942000000000029,
 0.10053999999999874,
 0.10970000000000013,
 0.03612999999999822,
 0.10055999999999976,
 0.10193999999999903,
 0.10040000000000049,
 0.09975000000000023,
 0.09919999999999973,
 0.1018100000000004,
 0.10192999999999941,
 0.09921000000000113,
 0.10239999999999938,
 0.09952999999999967,
 0.0996200000000016,
 0.10999999999999943,
 0.10032000000000174,
 0.10030000000000072,
 0.0992299999999986,
 0.109729999999999,
 0.10132000000000119,
 0.10023999999999944,
 0.10001000000000104,
 0.10042000000000151,
 0.0982899999999

In [53]:
ds = xr.Dataset()

In [54]:
ds

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*

In [ ]:
ds.to_netcdf('../MCMC_Data')